spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/smartcampus
spring.data.mongodb.auto-index-creation=true

# Datasource Configuration (for JPA if needed)
spring.datasource.url=jdbc:mysql://localhost:3306/smartcampus?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security Configuration
server.port=8080
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
