package com.smartcampus.backend.resources.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.List;// The Resource class represents a resource within the smart campus system. It includes fields for resource details such as asset ID, name, code, type, category, location, capacity, status, availability, and various attributes related to the resource. The class is annotated with Lombok annotations for boilerplate code generation and is mapped to a MongoDB collection named "resources". This model serves as the data structure for managing resources such as classrooms, labs, equipment, and facilities within the smart campus environment.

@Data// Lombok annotation to generate getters, setters, toString, equals, and hashCode methods for the Resource class, simplifying the code and improving readability.
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "resources")
public class Resource {
    @Id
    private String id;// The unique identifier for the resource, automatically generated by MongoDB when a new resource is created. This field is annotated with @Id to indicate that it serves as the primary key for the resource document in the MongoDB collection.
    private String assetId;
    private String name;
    private String code;
    private String type; // CLASSROOM, LAB, EQUIPMENT
    private String category;
    private String stockType;
    private String location;
    private int capacity;
    private String status; // AVAILABLE, MAINTAINANCE, OCCUPIED
    private Boolean available;
    private Integer serviceOrder;
    private String assignedTo;
    private String description;
    private List<String> amenities;
    private String image;// A URL or file path to an image representing the resource, which can be used for display purposes in the smart campus application. This field allows users to visually identify the resource and can enhance the user experience when browsing or managing resources within the system.
    private Integer totalPcs;
    private Integer workingPcs;
    private Integer smartBoardCount;
    private Integer workingSmartBoards;
    private Integer projectorCount;
    private Integer workingProjectors;// The projectorCount field represents the total number of projectors available for a resource, such as a classroom or lab, while the workingProjectors field indicates how many of those projectors are currently functional and available for use. This information is crucial for resource management and helps users determine the suitability of a resource for their needs based on the availability of essential equipment.
    private Integer screenCount;
    private Integer workingScreens;
    private Integer soundSystemCount;
    private Integer workingSoundSystems;
}
