import { useState } from 'react'

export function TechnicianAssignmentPanel({ technicians, onAssign }) {
  const [technicianId, setTechnicianId] = useState('')

  return (
    <div className="panel space-y-4">
      <h3 className="text-lg font-semibold text-slate-950">Assign Technician</h3>
      <select
        className="input"
        value={technicianId}
        onChange={(event) => setTechnicianId(event.target.value)}
      >//The select input allows the user to choose a technician from the list of available technicians passed as props. The first option is a placeholder prompting the user to select a technician, and the subsequent options are generated by mapping over the technicians array, creating an option element for each technician with their name displayed and their ID as the value. When a technician is selected, the technicianId state is updated accordingly, which can then be used when the "Assign Technician" button is clicked to trigger the onAssign function with the selected technician's ID.
        <option value="">Select technician</option>
        {technicians.map((technician) => (
          <option key={technician.id} value={technician.id}>
            {technician.name}
          </option>// The options for the select input are generated by mapping over the technicians array, which is passed as a prop to the TechnicianAssignmentPanel component. Each technician object in the array is expected to have an id and a name property. The option elements are created with the technician's name displayed to the user and the technician's ID set as the value of the option. This allows the user to select a technician from the dropdown, and when an option is selected, the technicianId state is updated with the corresponding technician's ID, which can then be used to assign the technician when the "Assign Technician" button is clicked.
        ))}
      </select>
      <button
        className="btn-primary w-full justify-center"
        type="button"
        onClick={() => onAssign(technicianId)}
      >
        Assign Technician
      </button>
    </div>// The "Assign Technician" button is a clickable element that triggers the onAssign function when clicked. The onAssign function is expected to be passed as a prop to the TechnicianAssignmentPanel component and should handle the logic for assigning the selected technician to a ticket or task. When the button is clicked, it calls the onAssign function with the current value of technicianId, which represents the ID of the technician selected from the dropdown. This allows the parent component to perform the necessary actions to assign the technician based on their ID, such as making an API call to update the ticket's assigned technician in the backend.
  )
}
