import { useState } from 'react'

export function TechnicianAssignmentPanel({ technicians, onAssign }) {
  const [technicianId, setTechnicianId] = useState('')

  return (
    <div className="panel space-y-4">
      <h3 className="text-lg font-semibold text-slate-950">Assign Technician</h3>
      <select
        className="input"
        value={technicianId}
        onChange={(event) => setTechnicianId(event.target.value)}
      >//The select input allows the user to choose a technician from the list of available technicians passed as props. The first option is a placeholder prompting the user to select a technician, and the subsequent options are generated by mapping over the technicians array, creating an option element for each technician with their name displayed and their ID as the value. When a technician is selected, the technicianId state is updated accordingly, which can then be used when the "Assign Technician" button is clicked to trigger the onAssign function with the selected technician's ID.
        <option value="">Select technician</option>
        {technicians.map((technician) => (
          <option key={technician.id} value={technician.id}>
            {technician.name}
          </option>
        ))}
      </select>
      <button
        className="btn-primary w-full justify-center"
        type="button"
        onClick={() => onAssign(technicianId)}
      >
        Assign Technician
      </button>
    </div>
  )
}
